#158839934 fix circleci notifications on failure (#71)
* [Chore #158839934] test deploy

* [Chore #158839934] test failure

* [Chore #158839934] create environment variable to determine slack notification on failure

* [Chore #158839934]  revert to testing all workflows

* [Chore #158839934] remove repeated steps

* [Chore #158839934] revert to copying java file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,6 +34,13 @@ export_gservices_key: &export_gservices_key
     name: Export Google Services key environment variable
     command: echo 'export GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON"' >> $BASH_ENV
 
+export_failure_determinant: &failure_determinant
+  run:
+    name: Export Failure Determinant
+    when: on_success
+    command: |
+      echo 'export INSTRUMENT_TEST_ARTIFACT=exempted' >> $BASH_ENV
+
 decode_gservices_key: &decode_gservices_key
   run:
     name: Decode Google Services JSON key
@@ -473,6 +480,7 @@ jobs:
       - *attach_debug_workspace
       - *export_gcloud_key
       - *decode_gcloud_key
+      - *failure_determinant
       - run:
           name: Set Google Cloud target project
           command: gcloud config set project andela-learning
@@ -480,16 +488,30 @@ jobs:
           name: Authenticate with Google Cloud
           command: gcloud auth activate-service-account mrm-android-editor@andela-learning.iam.gserviceaccount.com --key-file client-secret.json && gcloud firebase test android models list
       - run:
+          name: Notifying slack channel on fail
+          when: on_fail
+          command: |
+            if [ "${INSTRUMENT_TEST_ARTIFACT}" == exempted ]; then
+              bash ~/repo/.circleci/notify_slack_fail.sh
+            fi
+      - run:
+          name: Modify Failure Determinant
+          when: on_success
+          command: |
+            echo 'export INSTRUMENT_TEST_ARTIFACT=required' >> $BASH_ENV
+      - run:
           name: Run instrumented test on Firebase Test Lab
+          when: on_success
           command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/mock/debug/app-mock-debug.apk --test app/build/outputs/apk/androidTest/mock/debug/app-mock-debug-androidTest.apk --device model=Nexus7,version=22,locale=en,orientation=landscape --environment-variables coverage=true,coverageFile=/sdcard/coverage.ec --directories-to-pull=/sdcard --timeout 20m
       - run:
           name: Create directory to store test results
           command: mkdir firebase
       - run:
-          name: Download instrumented test results from Firebase Test Lab
+          name: Download instrumented test results from Firebase Test Lab on success
           command: gsutil -m cp -r -U "`gsutil ls gs://test-lab-42q965dw0t03q-w3crkis8m06h6 | tail -1`*" /root/repo/firebase/ || true
       - *persist_firebase_workspace
       - store_artifacts:
+          when: on_success
           path: firebase/
           destination: /firebase/
 
@@ -500,10 +522,24 @@ jobs:
           command: |
             bash ~/repo/.circleci/notify_slack.sh
       - run:
+          name: Download instrumented test results from Firebase Test Lab on fail fail
+          when: on_fail
+          command: |
+            if [ "$INSTRUMENT_TEST_ARTIFACT" == required ]; then
+              mkdir firebase
+              gsutil -m cp -r -U "`gsutil ls gs://test-lab-42q965dw0t03q-w3crkis8m06h6 | tail -1`*" /root/repo/firebase/ || true
+            fi
+      - store_artifacts:
+          when: on_fail
+          path: firebase/
+          destination: /firebase/
+      - run:
           name: Notifying slack channel on fail
           when: on_fail
           command: |
-            bash ~/repo/.circleci/notify_slack_fail.sh
+            if [ "$INSTRUMENT_TEST_ARTIFACT" == required ]; then
+              bash ~/repo/.circleci/notify_slack_fail.sh
+            fi
 
   report_coverage:
     <<: *defaults
